### ISSUE TITLE
Just installed a fronius system

### ISSUE THREAD

**Issue by fondberg** [nielstron/pyfronius#11]
Hi! I am a developer who has some home assistant knowledge and have just installed a fronius system with a smart meter. 

First off - great job on the module!

I have a couple of questions:
1. Are you open for PRs and collaboration (do you actively work and maintain) on pyfronius?
2. Do you have a custom component which uses pyfronius for home assistant?

**Comment by nielstron** [comment]
> Are you open for PRs and collaboration (do you actively work and maintain) on pyfronius?
Yes I am still open for developing this module
> Do you have a custom component which uses pyfronius for home assistant?
Yes. See [my pull request at home-assistant](https://github.com/home-assistant/home-assistant/pull/22316) and [the corresponding branch of my home-assistant fork](https://github.com/nielstron/home-assistant/tree/pyfronius).

**Comment by fondberg** [comment]
That is great news. What is stopping the PR from being merged? Do you need help with something?

**Comment by nielstron** [comment]
> What is stopping the PR from being merged?

Mostly time related issues. Feel free to have a look at the branch and open issues in the pull request, rebase/merge it to the current state of homeassistant:next and (re)open a pull request for it ;)

**Comment by fondberg** [comment]
Hey again! I've been busy for a while becuase me and my wife got another baby. I saw your great work with pushing the PR forward! Great job! A question, I have a smart meter 63, I'm guessing it is its own device id. Do you know how to list devices in the system?

**Comment by fondberg** [comment]
I tried to get the sensor which was merged in dev branch of HA but couldn't get it going. My conf is minimal
```
sensor:
  - platform: fronius
    resource: XXX
    monitored_conditions:
    - sensor_type: inverter
```
so I added _LOGGER.info in 
```
async def async_setup_platform(hass,
                               config,
                               async_add_entities,
                               discovery_info=None):
    """Set up of Fronius platform."""
    _LOGGER.info("Getting Fronius instance")
```
and couldn't see it. I can see the component being loaded but for some reason it never gets instanciated. Does the dev branch work for you?

**Comment by nielstron** [comment]
Hey! I am sorry to hear that it doesn't get instantiated on your system. On my system I have following configuration 
```yaml
sensor:
  - platform: fronius
    resource: http://ipp.ipp.ipp.ipp
    monitored_conditions:
    - sensor_type: inverter
    - sensor_type: inverter
      device: 3
    - sensor_type: meter
      scope: system
    - sensor_type: meter
    - sensor_type: storage
    - sensor_type: storage
      device: 5
    - sensor_type: power_flow
```

And get sensors as well as log output like the following
```
2019-07-14 23:55:37 INFO (MainThread) [pyfronius] No data returned from GetInverterRealtimeData.cgi?Scope=Device&DeviceId=3&DataCollection=CommonInverterData
2019-07-14 23:56:06 INFO (MainThread) [pyfronius] No data returned from GetStorageRealtimeData.cgi?Scope=Device&DeviceId=0
2019-07-14 23:56:06 INFO (MainThread) [pyfronius] No data returned from GetStorageRealtimeData.cgi?Scope=Device&DeviceId=5
2019-07-14 23:56:07 INFO (MainThread) [pyfronius] No data returned from GetInverterRealtimeData.cgi?Scope=Device&DeviceId=3&DataCollection=CommonInverterData
```

You can try adding some invalid sensor types (checking whether the configuration is included as expected by ha) and some sensor types that your device does not support (such that you get log output like mine).
