### ISSUE TITLE
Add `http://` to url if missing

### ISSUE THREAD

**Issue by farmio** [nielstron/pyfronius#33]
I have tried to configure the HA integration by only passing the IP address of my Datalogger, which failed because `http://` was missing. This could be automatically added to the url if not given.

```yaml
sensor:
  - platform: fronius
    resource: "http://10.1.2.5"  # I think this should also accept "10.1.2.5"
    monitored_conditions:
    - sensor_type: inverter
    - sensor_type: meter
    - sensor_type: power_flow
```
